import {CastleWorld,ROOMS,ROLES,TASKS} from './castle-world.js?v=6';
import {CastleRenderer} from './castle-renderer.js?v=14';
import {ForestAudio} from './audio.js?v=14';
import {formatClock} from './ecosystem.js?v=3';
const $=id=>document.getElementById(id),STORAGE='quiet-castle-v1',speeds=[.5,1,2,4];let saved=null;try{saved=JSON.parse(localStorage.getItem(STORAGE));}catch{}
const defaults={volume:50,music:32,'world-volume':85,fire:65,paper:80,fabric:70,pets:72,water:30,softness:94,intimacy:90,detail:45};
const presets={
 coast:{name:'Океан у стен',waterMode:3,hour:17,focus:'courtyard',temperature:20,wind:2,rain:0,candles:65,mix:{music:25,'world-volume':85,fire:25,paper:45,fabric:45,pets:65,water:45,softness:96,intimacy:85,detail:32}},
 hearth:{name:'Камин и бархат',waterMode:0,hour:19,focus:'hall',temperature:18,wind:1.5,rain:0,candles:80,mix:{music:30,'world-volume':85,fire:80,paper:65,fabric:78,pets:90,water:30,softness:95,intimacy:92,detail:48}},
 library:{name:'Дождь в библиотеке',waterMode:0,hour:16,focus:'library',temperature:16,wind:3,rain:.62,candles:65,mix:{music:22,'world-volume':90,fire:45,paper:95,fabric:45,pets:45,water:55,softness:94,intimacy:95,detail:55}},
 night:{name:'Сон замка',waterMode:0,hour:1,focus:'all',temperature:12,wind:1.5,rain:.2,candles:42,mix:{music:18,'world-volume':76,fire:75,paper:30,fabric:40,pets:80,water:30,softness:98,intimacy:90,detail:20}},
 morning:{name:'Утро во дворе',waterMode:2,hour:8,focus:'courtyard',temperature:22,wind:2,rain:0,candles:30,mix:{music:35,'world-volume':82,fire:15,paper:50,fabric:70,pets:55,water:25,softness:90,intimacy:78,detail:48}}
};
const world=new CastleWorld(saved?.world),renderer=new CastleRenderer($('world'),world);let running=false,busy=false,radioMode=!!saved?.radioMode,currentPreset=saved?(presets[saved.preset]?saved.preset:'custom'):'hearth',last=0,lastUI=0,lastSave=0,lastEvent=0,lastAudioTime=0;
const audio=new ForestAudio((active,error)=>{running=active;updateSound();if(error)$('audio-note').textContent=error;});
for(const [id,value]of Object.entries(defaults))$(id).value=Number.isFinite(saved?.mix?.[id])?Math.max(0,Math.min(100,saved.mix[id])):value;
$('sleep-timer').value=[0,15,30,60,120].includes(saved?.sleepMinutes)?saved.sleepMinutes:0;
function fill(el){el.style.setProperty('--fill',((Number(el.value)-Number(el.min))/(Number(el.max)-Number(el.min))*100)+'%');}
const savedWaterMode=saved?.waterMode;$('water-mode').value=Number.isInteger(savedWaterMode)&&savedWaterMode>=0&&savedWaterMode<=4?savedWaterMode:(presets[saved?.preset]?.waterMode??0);
if(saved?.soundVersion!==6)$('water').value=presets[saved?.preset]?.mix.water??30;
function save(){try{localStorage.setItem(STORAGE,JSON.stringify({soundVersion:6,waterMode:Number($('water-mode').value),world:world.snapshot(),mix:Object.fromEntries(Object.keys(defaults).map(id=>[id,Number($(id).value)])),preset:currentPreset,radioMode,sleepMinutes:Number($('sleep-timer').value)}));}catch{}}
function updateSound(){$('listen').setAttribute('aria-pressed',String(running));$('listen-text').textContent=running?'Выключить звук':audio.enabled?'Продолжить слушать':'Слушать замок';$('audio-note').textContent=audio.finished?'Таймер завершён. Замок тихо засыпает.':running?'Можно просто слушать. Или выбрать комнату и приблизить её звуки.':world.paused?'Замок замер. Нажми «Продолжить».':'Камин потрескивает, в комнатах слышны тихие касания и шаги. Нажми «Слушать замок».';}
function syncSound(){const focus=ROOMS.find(r=>r.id===world.focus),nearFire=world.focus==='hall'?1:world.focus==='all'?.7:world.focus==='library'?.38:.1;audio.setVolume(Number($('volume').value)/100);audio.setMix(Number($('music').value)/100,Number($('world-volume').value)/100);audio.setTexture({waterMode:Number($('water-mode').value),realm:1,inside:focus?(focus.indoor?1:0):.65,fire:world.fireplace*nearFire,paper:Number($('paper').value)/100,fabric:Number($('fabric').value)/100,pets:Number($('pets').value)/100,water:Number($('water').value)/100,leaves:world.focus==='garden'?.38:.08,calls:0,softness:Number($('softness').value)/100,intimacy:Number($('intimacy').value)/100,detail:Number($('detail').value)/100});audio.setEnvironment(world);}
function mixUI(){world.fireplace=Number($('fire').value)/100;for(const id of Object.keys(defaults)){$(id+'-value').textContent=$(id).value+'%';fill($(id));}syncSound();}
function presetUI(){$('preset-name').textContent=presets[currentPreset]?.name||'Своя атмосфера';document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset===currentPreset)));}
function custom(){currentPreset='custom';presetUI();}
function focusUI(){document.querySelectorAll('[data-room]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.room===world.focus)));const description={all:'Весь замок. Звуки доносятся из разных комнат.',hall:'Большой зал. Камин, тихие касания, чашки и мурчание.',library:'Библиотека. Касания книжной обложки и дождь по крыше.',bedroom:'Покои. Книга перед сном, мягкие касания и тихие шаги.',quarters:'Комнаты слуг. Отдых между делами и редкие мягкие постукивания.',kitchen:'Кухня. Чай льётся в чашки, повара замешивают тесто.',stables:'Конюшня. Деревянные постукивания, тихие шаги и забота о лошадях.',courtyard:'Двор. Тихая вода, ветер и шаги по каменным дорожкам.',garden:'Сад. Шорох листьев и маленькие заботы садовников.'};$('focus-description').textContent=description[world.focus];}
function chooseRoom(id){if(id!=='all'&&!ROOMS.some(r=>r.id===id))return;world.focus=id;focusUI();syncSound();save();}
function setRadio(value){radioMode=!!value;document.body.classList.toggle('radio-mode',radioMode);$('radio-mode').setAttribute('aria-pressed',String(radioMode));$('radio-mode').textContent=radioMode?'Наблюдать за жизнью':'Только слушать';}
function inspect(){const a=world.selected,r=ROLES[a.role],room=ROOMS.find(room=>room.id===a.room);$('agent-glyph').textContent=r.glyph;$('agent-glyph').style.color=r.color;const action=TASKS[a.action]||a.action;$('agent-action').textContent=action.charAt(0).toUpperCase()+action.slice(1);$('agent-reason').textContent=room.name+' · '+a.reason+'.';for(const [id,value]of [['need-food',1-a.hunger],['need-energy',a.energy],['need-comfort',a.comfort]]){$(id).value=value;$(id).textContent=Math.round(value*100)+'%';$(id).setAttribute('aria-valuetext',Math.round(value*100)+'%');}const friends=Object.keys(a.friends).length;$('agent-memory').textContent=(a.memory[0]||'Обживается в замке и знакомится с соседями.')+(friends?' Знакомых: '+friends+'.':'');}
function select(id){if(!Number.isInteger(id)||!world.agents[id])return;world.selectedId=id;$('agent-select').value=id;setRadio(false);inspect();save();}
function climateUI(){const values={temperature:Math.round(world.temperature),wind:Math.round((world.climate.wind??world.wind)*24)/2,'rain-level':Math.round((world.climate.rain??world.rain)*100),candles:Math.round(world.candles*100)};for(const [id,value]of Object.entries(values)){$(id).value=value;$(id+'-value').textContent=value+(id==='temperature'?' °C':id==='wind'?' м/с':'%');fill($(id));}$('hold-time').checked=world.holdTime;$('climate-effect').textContent=world.rain>.35?'Дождь загоняет жителей под крышу. Внутри теплее и тише.':world.temperature<6?'Холодно. Жители остаются в комнатах и ищут тепло.':world.temperature>31?'Жарко. Прогулки подождут: в залах прохладнее.':world.wind>.7?'Сильный ветер. Семья и слуги возвращаются из сада.':'Мягкая погода: можно гулять в саду и во дворе.';}
function updateUI(){
 $('clock').textContent=formatClock(world.time);$('period').textContent=world.period;$('awake-count').textContent=world.awake;$('scene-label').textContent=world.paused?'Замок на паузе':world.teaPending?'На кухне готовят чай':world.period==='Ночь'?'Замок спит, коты гуляют':'У каждого свои дела';$('time-flow').textContent=world.holdTime?'время закреплено':'время идёт';$('weather-mode-label').textContent=world.weatherMode==='auto'?'меняется сама':'твой выбор';
 $('weather-symbol').textContent=world.rain>.2?'☂':world.night>.7?'☾':'☀';$('weather-description').textContent=(world.rain>.2?'Дождь':world.fog>.3?'Туман':'Ясно')+' · '+Math.round(world.temperature)+'°';$('world-summary').textContent=world.teaPending?'Повара заваривают чай. Дворецкий скоро накроет стол и пригласит семью.':world.period==='Ночь'?'Семья и слуги отдыхают. Коты бродят между библиотекой и камином.':world.badWeather()?'Прогулки подождут. Жители читают, готовят и заботятся друг о друге внутри замка.':'Слуги заняты делами, семья выбирает между книгами и садом, звери ищут уютные места.';
 document.querySelectorAll('[data-time]').forEach(b=>{const periods={7:'Утро',13:'День',19:'Вечер',1:'Ночь'},active=periods[b.dataset.time]===world.period;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});document.querySelectorAll('[data-weather]').forEach(b=>{const active=b.dataset.weather===world.weatherMode;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});
 if(lastEvent!==world.eventId){lastEvent=world.eventId;const f=document.createDocumentFragment();for(const event of world.events.slice(0,5)){const li=document.createElement('li'),time=document.createElement('time'),text=document.createElement('span');time.textContent=formatClock(event.time);text.textContent=event.text;li.append(time,text);if(event.agentId!==null){li.tabIndex=0;li.setAttribute('role','button');li.addEventListener('click',()=>select(event.agentId));li.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(event.agentId);}});}f.append(li);}$('events').replaceChildren(f);}climateUI();inspect();
}
function applyPreset(key,persist=true){const p=presets[key];if(!p)return;currentPreset=key;$('water-mode').value=p.waterMode;for(const [id,value]of Object.entries(p.mix))$(id).value=value;world.setTime(p.hour);world.holdTime=true;world.setWeather(p.rain?'rain':'clear');world.setClimate('temperature',p.temperature);world.setClimate('wind',p.wind/12);world.setClimate('rain',p.rain);world.candles=p.candles/100;world.focus=p.focus;mixUI();focusUI();presetUI();updateUI();if(persist)save();}
async function pause(paused){world.paused=paused;$('pause').textContent=paused?'Продолжить':'Замереть';$('pause').setAttribute('aria-pressed',String(paused));await audio.setPaused(paused);updateUI();updateSound();}
async function start(){if(world.paused)await pause(false);syncSound();await audio.enable();}
$('listen').addEventListener('click',async()=>{if(busy)return;busy=true;$('listen').disabled=true;try{if(running)await audio.disable();else await start();}catch(error){$('audio-note').textContent=error.message||'Не удалось включить звук. Нажми ещё раз.';}finally{busy=false;$('listen').disabled=false;}});
$('pause').addEventListener('click',()=>void pause(!world.paused));$('radio-mode').addEventListener('click',()=>{setRadio(!radioMode);save();});
for(const id of Object.keys(defaults))$(id).addEventListener('input',()=>{if(id!=='volume')custom();mixUI();save();});
for(const [id,key,divisor]of [['temperature','temperature',1],['wind','wind',12],['rain-level','rain',100]])$(id).addEventListener('input',()=>{custom();world.setClimate(key,Number($(id).value)/divisor);climateUI();syncSound();save();});
$('candles').addEventListener('input',()=>{world.candles=Number($('candles').value)/100;climateUI();save();});$('hold-time').addEventListener('change',()=>{world.holdTime=$('hold-time').checked;updateUI();save();});$('auto-climate').addEventListener('click',()=>{custom();world.autoClimate();updateUI();save();});
$('speed').value=Math.max(0,speeds.indexOf(world.speed));function speedUI(){$('speed-value').textContent=['Медленный','Обычный','Быстрый','Очень быстрый'][Number($('speed').value)];fill($('speed'));}$('speed').addEventListener('input',()=>{world.speed=speeds[Number($('speed').value)];speedUI();save();});
$('water-mode').addEventListener('change',()=>{custom();mixUI();save();});
$('sleep-timer').addEventListener('change',()=>{audio.setSleep(Number($('sleep-timer').value));$('timer-left').textContent=audio.sleepMinutes?'плавное затихание':'';save();});
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>applyPreset(b.dataset.preset)));document.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>{custom();world.setTime(Number(b.dataset.time));updateUI();syncSound();save();}));document.querySelectorAll('[data-weather]').forEach(b=>b.addEventListener('click',()=>{custom();world.setWeather(b.dataset.weather);updateUI();save();}));
for(const room of [{id:'all',name:'Весь замок',icon:'♔'},...ROOMS]){const b=document.createElement('button');b.dataset.room=room.id;b.textContent=room.icon+' '+room.name;b.setAttribute('aria-pressed',String(world.focus===room.id));b.addEventListener('click',()=>chooseRoom(room.id));$('room-list').append(b);}
for(const groupName of ['Королевская семья','Слуги','Звери']){const group=document.createElement('optgroup');group.label=groupName;for(const a of world.agents.filter(a=>ROLES[a.role].group===groupName)){const option=document.createElement('option');option.value=a.id;option.textContent=a.name;group.append(option);}$('agent-select').append(group);}$('agent-select').value=world.selectedId;$('agent-select').addEventListener('change',()=>select(Number($('agent-select').value)));
$('world').addEventListener('pointerup',e=>{const hit=renderer.hit(e.clientX,e.clientY);if(hit.agent!==undefined)select(hit.agent);else if(hit.room)chooseRoom(hit.room);});$('paths').addEventListener('click',()=>{renderer.showPaths=!renderer.showPaths;$('paths').setAttribute('aria-pressed',String(renderer.showPaths));$('paths').textContent=renderer.showPaths?'Пути видны':'Показать пути';});
$('invite-tea').addEventListener('click',()=>{$('interaction-note').textContent=world.requestTea()?'Повара готовят чай. Дворецкий накроет стол, и семья придёт в зал.':world.paused?'Сначала продолжи жизнь замка.':'Приготовления уже идут. Дай жителям немного времени.';updateUI();save();});$('feed-pets').addEventListener('click',()=>{$('interaction-note').textContent=world.feedPets()?'В конюшне разложили угощение. Звери идут к нему.':'Сначала продолжи жизнь замка.';updateUI();save();});
$('about-toggle').addEventListener('click',()=>{const open=$('about-toggle').getAttribute('aria-expanded')!=='true';$('about-toggle').setAttribute('aria-expanded',String(open));$('about').hidden=!open;});
audio.onHeartbeat=m=>{const dt=lastAudioTime?Math.min(5,Math.max(0,m.time-lastAudioTime)):1;lastAudioTime=m.time;if(document.hidden&&audio.enabled&&!world.paused){for(let t=0;t<dt;t+=.2)world.tick(Math.min(.2,dt-t));for(const event of world.drain())audio.song(event);audio.setEnvironment(world);if(performance.now()-lastSave>8000){save();lastSave=performance.now();}}$('timer-left').textContent=m.remaining>0?Math.ceil(m.remaining/60)+' мин осталось':'';};audio.onSleep=()=>{$('timer-left').textContent='Готово';updateSound();};
try{if(navigator.mediaSession){if(window.MediaMetadata)navigator.mediaSession.metadata=new MediaMetadata({title:'Королевский замок',artist:'Тихие миры',album:'Камин, страницы и маленькая жизнь'});navigator.mediaSession.setActionHandler('play',()=>void start().catch(e=>{$('audio-note').textContent=e.message;}));navigator.mediaSession.setActionHandler('pause',()=>void audio.disable());navigator.mediaSession.setActionHandler('stop',()=>void audio.disable());}}catch{}
document.addEventListener('visibilitychange',()=>{last=0;save();void audio.setHidden(document.hidden);});window.addEventListener('pagehide',()=>{save();void audio.disable();});renderer.ready.then(()=>{$('scene-loading').hidden=true;renderer.render();}).catch(()=>{$('scene-loading').textContent='Не удалось загрузить замок. Обнови страницу.';});
function frame(t){if(!document.hidden){const dt=last?Math.min(.1,(t-last)/1000):0;world.tick(dt);for(const event of world.drain())audio.song(event);renderer.render();if(t-lastUI>300){updateUI();audio.setEnvironment(world);lastUI=t;}if(t-lastSave>8000){save();lastSave=t;}}last=t;requestAnimationFrame(frame);}
if(!saved)applyPreset('hearth',false);setRadio(radioMode);mixUI();focusUI();presetUI();climateUI();speedUI();updateUI();audio.setSleep(Number($('sleep-timer').value));requestAnimationFrame(frame);
