import {CityWorld,PLACES,ROLES,TASKS} from './city-world.js?v=6';
import {CityRenderer} from './city-renderer.js?v=8';
import {ForestAudio} from './audio.js?v=11';
import {formatClock} from './ecosystem.js?v=3';
const $=id=>document.getElementById(id),STORAGE='quiet-city-v1',speeds=[.5,1,2,4];let saved=null;try{saved=JSON.parse(localStorage.getItem(STORAGE));}catch{}
const defaults={water:35,volume:50,music:52,'world-volume':86,cafe:88,people:42,street:36,tram:32,pets:62,softness:95,intimacy:87,detail:44};
const presets={
 neighbors:{name:'Вечер с соседями',waterMode:0,hour:18,focus:'cafe',temperature:21,wind:1,rain:0,lights:85,mix:{water:35,music:52,'world-volume':86,cafe:88,people:48,street:30,tram:24,pets:70,softness:95,intimacy:87,detail:48}},
 rain:{name:'Дождливое кафе',waterMode:0,hour:16,focus:'cafe',temperature:17,wind:2,rain:.62,lights:75,mix:{water:55,music:45,'world-volume':88,cafe:90,people:30,street:18,tram:15,pets:60,softness:96,intimacy:92,detail:36}},
 morning:{name:'Утро в пекарне',waterMode:0,hour:8,focus:'bakery',temperature:22,wind:1.5,rain:0,lights:35,mix:{water:30,music:57,'world-volume':84,cafe:95,people:35,street:40,tram:35,pets:45,softness:93,intimacy:86,detail:50}},
 night:{name:'Ночные окна',waterMode:0,hour:23.5,focus:'home',temperature:15,wind:1,rain:.16,lights:68,mix:{water:28,music:38,'world-volume':74,cafe:28,people:12,street:18,tram:0,pets:65,softness:98,intimacy:90,detail:20}}
};
const world=new CityWorld(saved?.world),renderer=new CityRenderer($('world'),world);let running=false,busy=false,radioMode=saved?.radioMode??true,currentPreset=saved?(presets[saved.preset]?saved.preset:'custom'):'neighbors',last=0,lastUI=0,lastSave=0,lastEvent=0,lastAudioTime=0;
const audio=new ForestAudio((active,error)=>{running=active;updateSound();if(error)$('audio-note').textContent=error;});
for(const [id,value]of Object.entries(defaults))$(id).value=Number.isFinite(saved?.mix?.[id])?Math.max(0,Math.min(100,saved.mix[id])):value;
$('sleep-timer').value=[0,15,30,60,120].includes(saved?.sleepMinutes)?saved.sleepMinutes:0;
function fill(el){el.style.setProperty('--fill',((Number(el.value)-Number(el.min))/(Number(el.max)-Number(el.min))*100)+'%');}
const savedWaterMode=saved?.waterMode;$('water-mode').value=Number.isInteger(savedWaterMode)&&savedWaterMode>=0&&savedWaterMode<=4?savedWaterMode:(presets[saved?.preset]?.waterMode??0);
if(saved?.soundVersion!==6)$('water').value=presets[saved?.preset]?.mix.water??35;
function save(){try{localStorage.setItem(STORAGE,JSON.stringify({soundVersion:6,waterMode:Number($('water-mode').value),world:world.snapshot(),mix:Object.fromEntries(Object.keys(defaults).map(id=>[id,Number($(id).value)])),preset:currentPreset,radioMode,sleepMinutes:Number($('sleep-timer').value)}));}catch{}}
function updateSound(){$('listen').setAttribute('aria-pressed',String(running));$('listen-text').textContent=running?'Выключить радио':audio.enabled?'Продолжить слушать':'Слушать город';$('audio-note').textContent=audio.finished?'Таймер завершён. В окнах гаснет свет.':running?'Кто-то наливает кофе. Кто-то читает рядом. Можно просто побыть здесь.':world.paused?'Город замер. Нажми «Продолжить».':'Мягкое пианино и маленькие дела рядом. Нажми «Слушать город».';}
function syncSound(){const focus=PLACES.find(r=>r.id===world.focus);audio.setVolume(Number($('volume').value)/100);audio.setMix(Number($('music').value)/100,Number($('world-volume').value)/100);audio.setTexture({waterMode:Number($('water-mode').value),realm:2,inside:focus?(focus.indoor?1:0):.45,fire:0,water:Number($('water').value)/100,leaves:world.focus==='park'?.45:.05,calls:0,...Object.fromEntries(['cafe','people','street','tram','pets','softness','intimacy','detail'].map(id=>[id,Number($(id).value)/100]))});audio.setEnvironment(world);}
function mixUI(){for(const id of Object.keys(defaults)){$(id+'-value').textContent=$(id).value+'%';fill($(id));}syncSound();}
function presetUI(){$('preset-name').textContent=presets[currentPreset]?.name||'Своя атмосфера';document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset===currentPreset)));}
function custom(){currentPreset='custom';presetUI();}
function focusUI(){document.querySelectorAll('[data-place]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.place===world.focus)));const description={all:'Весь квартал. Небольшие дела складываются в жизнь города.',home:'Тёплые окна. Книга, чашка и тихий вечер дома.',bakery:'Пекарня. Мягкие касания деревянного стола и знакомые посетители.',cafe:'Кафе. Чашки, отдельные капли кофе и тёплые музыкальные отклики соседей.',bookshop:'Книжная лавка. Тихие касания книг, посетители и кот между полок.',park:'Тихий сад. Листья, полив цветов и звери на дорожках.',square:'Площадь. Размеренные шаги и встречи знакомых соседей.',stop:'Остановка. Неспешные пассажиры и редкий негромкий звонок трамвая.'};$('focus-description').textContent=description[world.focus];}
function choosePlace(id){if(id!=='all'&&!PLACES.some(r=>r.id===id))return;world.focus=id;focusUI();syncSound();save();}
function setRadio(value){radioMode=!!value;document.body.classList.toggle('radio-mode',radioMode);$('radio-mode').setAttribute('aria-pressed',String(radioMode));$('radio-mode').textContent=radioMode?'Наблюдать за жизнью':'Только слушать';}
function inspect(){const a=world.selected,r=ROLES[a.role],room=PLACES.find(room=>room.id===a.place);$('agent-glyph').textContent=r.glyph;$('agent-glyph').style.color=r.color;const action=TASKS[a.action]||a.action;$('agent-action').textContent=action.charAt(0).toUpperCase()+action.slice(1);$('agent-reason').textContent=room.name+' · '+a.reason+'.';for(const [id,value]of [['need-food',1-a.hunger],['need-energy',a.energy],['need-comfort',a.comfort]]){$(id).value=value;$(id).textContent=Math.round(value*100)+'%';$(id).setAttribute('aria-valuetext',Math.round(value*100)+'%');}const friends=Object.keys(a.friends).length;$('agent-memory').textContent=(a.memory[0]||'Обживается в квартале и запоминает соседей.')+(friends?' Знакомых: '+friends+'.':'');}
function select(id){if(!Number.isInteger(id)||!world.agents[id])return;world.selectedId=id;$('agent-select').value=id;setRadio(false);inspect();save();}
function climateUI(){const values={temperature:Math.round(world.temperature),wind:Math.round((world.climate.wind??world.wind)*24)/2,'rain-level':Math.round((world.climate.rain??world.rain)*100),lights:Math.round(world.lights*100)};for(const [id,value]of Object.entries(values)){$(id).value=value;$(id+'-value').textContent=value+(id==='temperature'?' °C':id==='wind'?' м/с':'%');fill($(id));}$('hold-time').checked=world.holdTime;$('climate-effect').textContent=world.rain>.35?'В дождь соседи заходят в кафе и книжную лавку.':world.temperature<6?'В холод жители выбирают тёплые дома и кафе.':world.temperature>31?'Жарко. Жители отдыхают в помещениях и пьют прохладные напитки.':world.wind>.7?'Ветер усилился. Во дворе становится тише, дома — уютнее.':'Мягкая погода: соседи гуляют, встречаются и ухаживают за цветами.';}
function updateUI(){
 $('clock').textContent=formatClock(world.time);$('period').textContent=world.period;$('awake-count').textContent=world.awake;$('scene-label').textContent=world.paused?'Город на паузе':world.invitePhase==='brewing'?'В кафе готовят встречу':world.invitePhase==='ready'?'Соседи за одним столом':world.period==='Ночь'?'Тёплые окна, тихие улицы':'Здесь всегда свои маленькие дела';$('time-flow').textContent=world.holdTime?'время закреплено':'время идёт';$('weather-mode-label').textContent=world.weatherMode==='auto'?'меняется сама':'твой выбор';
 $('weather-symbol').textContent=world.rain>.2?'☂':world.night>.7?'☾':'☀';$('weather-description').textContent=(world.rain>.2?'Дождь':world.fog>.3?'Туман':'Ясно')+' · '+Math.round(world.temperature)+'°';$('world-summary').textContent=world.invitePhase==='brewing'?'Бариста готовит напитки. Скоро соседи соберутся за одним столом.':world.invitePhase==='ready'?'В кафе идёт встреча. За чашкой кофе соседи узнают друг друга ближе.':world.period==='Ночь'?'Большинство жителей спят. Смотритель заканчивает обход, коты выбирают мягкие места.':world.badWeather()?'С улиц перебираются под крышу: в кафе, книжную лавку и свои тёплые дома.':'В пекарне месят тесто, в кафе наливают кофе. Между делами соседи встречаются и знакомятся.';
 document.querySelectorAll('[data-time]').forEach(b=>{const periods={8:'Утро',13:'День',18:'Вечер',1:'Ночь'},active=periods[b.dataset.time]===world.period;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});document.querySelectorAll('[data-weather]').forEach(b=>{const active=b.dataset.weather===world.weatherMode;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});
 if(lastEvent!==world.eventId){lastEvent=world.eventId;const f=document.createDocumentFragment();for(const event of world.events.slice(0,5)){const li=document.createElement('li'),time=document.createElement('time'),text=document.createElement('span');time.textContent=formatClock(event.time);text.textContent=event.text;li.append(time,text);if(event.agentId!==null){li.tabIndex=0;li.setAttribute('role','button');li.addEventListener('click',()=>select(event.agentId));li.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(event.agentId);}});}f.append(li);}$('events').replaceChildren(f);}climateUI();inspect();
}
function applyPreset(key,persist=true){const p=presets[key];if(!p)return;currentPreset=key;$('water-mode').value=p.waterMode;for(const [id,value]of Object.entries(p.mix))$(id).value=value;world.setTime(p.hour);world.holdTime=true;world.setWeather(p.rain?'rain':'clear');world.setClimate('temperature',p.temperature);world.setClimate('wind',p.wind/12);world.setClimate('rain',p.rain);world.lights=p.lights/100;world.focus=p.focus;mixUI();focusUI();presetUI();updateUI();if(persist)save();}
async function pause(paused){world.paused=paused;$('pause').textContent=paused?'Продолжить':'Замереть';$('pause').setAttribute('aria-pressed',String(paused));await audio.setPaused(paused);updateUI();updateSound();}
async function start(){if(world.paused)await pause(false);syncSound();await audio.enable();}
$('listen').addEventListener('click',async()=>{if(busy)return;busy=true;$('listen').disabled=true;try{if(running)await audio.disable();else await start();}catch(error){$('audio-note').textContent=error.message||'Не удалось включить звук. Нажми ещё раз.';}finally{busy=false;$('listen').disabled=false;}});
$('pause').addEventListener('click',()=>void pause(!world.paused));$('radio-mode').addEventListener('click',()=>{setRadio(!radioMode);save();});
for(const id of Object.keys(defaults))$(id).addEventListener('input',()=>{if(id!=='volume')custom();mixUI();save();});
for(const [id,key,divisor]of [['temperature','temperature',1],['wind','wind',12],['rain-level','rain',100]])$(id).addEventListener('input',()=>{custom();world.setClimate(key,Number($(id).value)/divisor);climateUI();syncSound();save();});
$('lights').addEventListener('input',()=>{world.lights=Number($('lights').value)/100;climateUI();save();});$('hold-time').addEventListener('change',()=>{world.holdTime=$('hold-time').checked;updateUI();save();});$('auto-climate').addEventListener('click',()=>{custom();world.autoClimate();updateUI();save();});
$('speed').value=Math.max(0,speeds.indexOf(world.speed));function speedUI(){$('speed-value').textContent=['Медленный','Обычный','Быстрый','Очень быстрый'][Number($('speed').value)];fill($('speed'));}$('speed').addEventListener('input',()=>{world.speed=speeds[Number($('speed').value)];speedUI();save();});
$('water-mode').addEventListener('change',()=>{custom();mixUI();save();});
$('sleep-timer').addEventListener('change',()=>{audio.setSleep(Number($('sleep-timer').value));$('timer-left').textContent=audio.sleepMinutes?'плавное затихание':'';save();});
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>applyPreset(b.dataset.preset)));document.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>{custom();world.setTime(Number(b.dataset.time));updateUI();syncSound();save();}));document.querySelectorAll('[data-weather]').forEach(b=>b.addEventListener('click',()=>{custom();world.setWeather(b.dataset.weather);updateUI();save();}));
for(const room of [{id:'all',name:'Весь квартал',icon:'⌂'},...PLACES]){const b=document.createElement('button');b.dataset.place=room.id;b.textContent=room.icon+' '+room.name;b.setAttribute('aria-pressed',String(world.focus===room.id));b.addEventListener('click',()=>choosePlace(room.id));$('place-list').append(b);}
for(const groupName of ['Соседи','Маленькие дела','Звери']){const group=document.createElement('optgroup');group.label=groupName;for(const a of world.agents.filter(a=>ROLES[a.role].group===groupName)){const option=document.createElement('option');option.value=a.id;option.textContent=a.name;group.append(option);}$('agent-select').append(group);}$('agent-select').value=world.selectedId;$('agent-select').addEventListener('change',()=>select(Number($('agent-select').value)));
$('world').addEventListener('pointerup',e=>{const hit=renderer.hit(e.clientX,e.clientY);if(hit.agent!==undefined)select(hit.agent);else if(hit.place)choosePlace(hit.place);});$('paths').addEventListener('click',()=>{renderer.showPaths=!renderer.showPaths;$('paths').setAttribute('aria-pressed',String(renderer.showPaths));$('paths').textContent=renderer.showPaths?'Пути видны':'Показать пути';});
$('invite-coffee').addEventListener('click',()=>{$('interaction-note').textContent=world.requestCoffee()?'Кофе скоро будет готов. Бариста пригласит соседей за один стол.':world.paused?'Сначала продолжи жизнь города.':'Приготовления уже идут. Дай жителям немного времени.';updateUI();save();});$('feed-pets').addEventListener('click',()=>{$('interaction-note').textContent=world.feedPets()?'У кафе появилось угощение. Звери идут к нему.':'Сначала продолжи жизнь города.';updateUI();save();});
$('about-toggle').addEventListener('click',()=>{const open=$('about-toggle').getAttribute('aria-expanded')!=='true';$('about-toggle').setAttribute('aria-expanded',String(open));$('about').hidden=!open;});
audio.onHeartbeat=m=>{const dt=lastAudioTime?Math.min(5,Math.max(0,m.time-lastAudioTime)):1;lastAudioTime=m.time;if(document.hidden&&audio.enabled&&!world.paused){for(let t=0;t<dt;t+=.2)world.tick(Math.min(.2,dt-t));for(const event of world.drain())audio.song(event);audio.setEnvironment(world);if(performance.now()-lastSave>8000){save();lastSave=performance.now();}}$('timer-left').textContent=m.remaining>0?Math.ceil(m.remaining/60)+' мин осталось':'';};audio.onSleep=()=>{$('timer-left').textContent='Готово';updateSound();};
try{if(navigator.mediaSession){if(window.MediaMetadata)navigator.mediaSession.metadata=new MediaMetadata({title:'Город рядом',artist:'Тихие миры',album:'Пианино, кофе и знакомые окна'});navigator.mediaSession.setActionHandler('play',()=>void start().catch(e=>{$('audio-note').textContent=e.message;}));navigator.mediaSession.setActionHandler('pause',()=>void audio.disable());navigator.mediaSession.setActionHandler('stop',()=>void audio.disable());}}catch{}
document.addEventListener('visibilitychange',()=>{last=0;save();void audio.setHidden(document.hidden);});window.addEventListener('pagehide',()=>{save();void audio.disable();});renderer.ready.then(()=>{$('scene-loading').hidden=true;renderer.render();}).catch(()=>{$('scene-loading').textContent='Не удалось загрузить город. Обнови страницу.';});
function frame(t){if(!document.hidden){const dt=last?Math.min(.1,(t-last)/1000):0;world.tick(dt);for(const event of world.drain())audio.song(event);renderer.render();if(t-lastUI>300){updateUI();audio.setEnvironment(world);lastUI=t;}if(t-lastSave>8000){save();lastSave=t;}}last=t;requestAnimationFrame(frame);}
if(!saved)applyPreset('neighbors',false);setRadio(radioMode);mixUI();focusUI();presetUI();climateUI();speedUI();updateUI();audio.setSleep(Number($('sleep-timer').value));requestAnimationFrame(frame);
