export const SPECIES = [
 {name:'Синица',plural:'Птицы',color:'#e7cc63',glyph:'△',count:12,pace:.046,voice:'bird',social:.8},
 {name:'Белка',plural:'Белки',color:'#e59969',glyph:'◇',count:8,pace:.031,voice:'rustle',social:.45},
 {name:'Пчела',plural:'Пчёлы',color:'#d6da6c',glyph:'✧',count:18,pace:.032,voice:'bee',social:.3},
 {name:'Дятел',plural:'Дятлы',color:'#d696ac',glyph:'✳',count:4,pace:.038,voice:'wood',social:.4},
 {name:'Ворона',plural:'Вороны',color:'#acaed3',glyph:'▽',count:4,pace:.037,voice:'crow',social:.7},
 {name:'Лиса',plural:'Лисы',color:'#e59b67',glyph:'□',count:2,pace:.019,voice:'step',social:.12},
 {name:'Сова',plural:'Совы',color:'#bbbcdd',glyph:'◈',count:2,pace:.032,voice:'owl',social:.45,nocturnal:true},
 {name:'Светлячок',plural:'Светлячки',color:'#d9f19b',glyph:'·',count:18,pace:.016,voice:'glow',social:.5,nocturnal:true}
];
export const formatClock=m=>`${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(Math.floor(m)%60).padStart(2,'0')}`;
export const ACTIONS={idle:'прислушивается',seekFood:'ищет еду',eat:'ест семена',gather:'собирает запас',cache:'прячет семечко',seekWater:'идёт к воде',drink:'пьёт из ручья',goHome:'возвращается домой',rest:'отдыхает',sleep:'спит',wander:'исследует поляну',approach:'идёт к соседу',social:'общается с соседом',sing:'поёт',pollinate:'собирает нектар',flee:'ищет безопасное место',shelter:'отдыхает в укрытии',patrol:'обходит территорию',peck:'стучит по дереву'};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export class Ecosystem {
 constructor(saved=null){
  this.seed=(saved?.seed>>>0)||((Date.now()^0x5e394b)>>>0);this.elapsed=0;this.time=Number.isFinite(saved?.time)?((saved.time%1440)+1440)%1440:460;this.speed=[.5,1,2,4].includes(saved?.speed)?saved.speed:1;
  this.weatherMode=['auto','clear','rain','fog','custom'].includes(saved?.weatherMode)?saved.weatherMode:'auto';this.weather=['clear','rain','fog'].includes(saved?.weather)?saved.weather:'clear';this.rain=0;this.fog=0;this.wind=.2;this.weatherAge=0;this.weatherDuration=65+this.random()*45;this.paused=false;this.events=[];this.outbox=[];this.eventId=0;this.lastLog=-10;this.connections=[];this.ripples=[];this.pending=[];this.lastCall=-20;this.lastEnvironmentLog=-10;this.selectedId=Number.isInteger(saved?.selectedId)?saved.selectedId:0;
  this.climate={temperature:Number.isFinite(saved?.climate?.temperature)?clamp(saved.climate.temperature,-5,35):null,wind:Number.isFinite(saved?.climate?.wind)?clamp(saved.climate.wind):null,rain:Number.isFinite(saved?.climate?.rain)?clamp(saved.climate.rain):null};this.holdTime=!!saved?.holdTime;this.lastFeed=-30;
  this.resources=[{id:0,x:.37,y:.55,kind:'seed',stock:.95},{id:1,x:.56,y:.64,kind:'seed',stock:.8},{id:2,x:.5,y:.43,kind:'seed',stock:.9},{id:3,x:.27,y:.64,kind:'seed',stock:.8},{id:4,x:.27,y:.49,kind:'flower',stock:1},{id:5,x:.64,y:.52,kind:'flower',stock:.9},{id:6,x:.47,y:.62,kind:'flower',stock:.8},{id:7,x:.736,y:.602,kind:'water',stock:1}];
  this.agents=[];for(let species=0;species<SPECIES.length;species++)for(let i=0;i<SPECIES[species].count;i++){const home=this.point(species),s=SPECIES[species],id=this.agents.length;this.agents.push({id,species,name:s.name+' '+String(i+1).padStart(2,'0'),x:home.x,y:home.y,home,energy:.55+this.random()*.4,hunger:.28+this.random()*.45,thirst:.2+this.random()*.4,stress:0,curiosity:.3+this.random()*.6,sociability:s.social*(.7+this.random()*.5),action:'idle',reason:'прислушивается к соседям',target:null,targetId:null,until:0,decisionAt:this.random()*3,voiceAt:3+this.random()*10,step:0,phase:this.random()*6.28,signal:0,friends:{},memory:[],carrying:false,cacheCount:0,visits:0});}
  if(saved?.version>=2&&Array.isArray(saved.agents))for(const a of this.agents){const p=saved.agents.find(q=>q.id===a.id&&q.species===a.species);if(!p)continue;for(const k of ['x','y','energy','hunger','thirst','stress'])if(Number.isFinite(p[k]))a[k]=clamp(p[k]);a.friends=p.friends&&typeof p.friends==='object'?p.friends:{};a.memory=Array.isArray(p.memory)?p.memory.filter(x=>typeof x==='string').slice(0,3):[];a.cacheCount=Number.isFinite(p.cacheCount)?p.cacheCount:0;}
  this.updateLight();this.emit(saved?'Мир продолжается с того же момента.':'Обитатели просыпаются и выбирают свои занятия.','world',null,true);
 }
 random(){let x=this.seed;x^=x<<13;x^=x>>>17;x^=x<<5;this.seed=x>>>0;return this.seed/4294967296;}
 point(species=0){const homes=[[.2,.4],[.31,.34],[.43,.27],[.63,.31],[.77,.37],[.83,.48],[.25,.55],[.4,.44],[.56,.48],[.64,.56]];if(species===2)return{x:.28+this.random()*.36,y:.47+this.random()*.18};if(species===5)return{x:.25+this.random()*.4,y:.5+this.random()*.2};if(species===7)return{x:.23+this.random()*.53,y:.38+this.random()*.32};const p=homes[Math.floor(this.random()*homes.length)];return{x:p[0]+(this.random()-.5)*.05,y:p[1]+(this.random()-.5)*.03};}
 updateLight(){const h=this.time/60;this.daylight=clamp((Math.sin((h-6)*Math.PI/12)+.28)*1.22);this.night=1-this.daylight;this.dawn=clamp(1-Math.abs(h-7)/2.5);this.dusk=clamp(1-Math.abs(h-18.4)/2);this.period=h<5||h>=21?'Ночь':h<9?'Рассвет':h<17?'День':'Закат';this.temperature=this.climate.temperature??(12+this.daylight*10-this.rain*3);}
 emit(text,type='life',id=null,force=false){if(id!==null){const a=this.agents[id];a.memory.unshift(text);a.memory.length=Math.min(a.memory.length,3);}if(!force&&this.elapsed-this.lastLog<1.1)return;this.lastLog=this.elapsed;this.events.unshift({id:++this.eventId,text,type,agentId:id,time:this.time});this.events.length=Math.min(this.events.length,8);}
 action(a,kind,reason,target=null,duration=4){a.action=kind;a.reason=reason;a.target=target?{x:target.x,y:target.y}:null;a.until=this.elapsed+duration;a.decisionAt=this.elapsed+.8;}
 sound(a,kind=SPECIES[a.species].voice,detail=''){a.signal=1;this.outbox.push({type:'event',kind,id:a.id,species:a.species,pan:clamp((a.x-.5)*2,-.9,.9),variation:this.random(),note:a.id%5,detail,energy:a.energy});}
 nearestResource(a,kind){return this.resources.filter(r=>r.kind===kind&&r.stock>.08).sort((x,y)=>dist(a,x)-dist(a,y))[0]||this.resources.find(r=>r.kind===kind);}
 peer(a){return this.agents.filter(b=>b.id!==a.id&&b.species===a.species&&!['sleep','shelter','flee'].includes(b.action)&&dist(a,b)<.27).sort((b,c)=>((a.friends[c.id]||0)*.04-dist(a,c))-((a.friends[b.id]||0)*.04-dist(a,b)))[0];}
 setTime(hour){if(!Number.isFinite(hour))return;this.time=((hour%24)+24)%24*60;this.updateLight();this.pending=[];for(const a of this.agents){a.decisionAt=this.elapsed;a.until=this.elapsed;}this.emit({Рассвет:'Рассвет: дневные обитатели возвращаются к своим делам.',День:'Полдень: на поляне становится оживлённее.',Закат:'Вечер: обитатели собираются домой.',Ночь:'Ночь: просыпаются совы и светлячки.'}[this.period],'world',null,true);}
 setWeather(mode){if(!['auto','clear','rain','fog'].includes(mode))return;this.climate.rain=null;this.weatherMode=mode;if(mode==='auto'){this.weatherAge=0;this.weatherDuration=35+this.random()*45;this.emit('Погода снова меняется сама.','weather',null,true);}else this.changeWeather(mode);}
 changeWeather(w){if(this.weather===w)return;this.weather=w;this.weatherAge=0;this.weatherDuration=65+this.random()*65;this.emit({clear:'Облака расходятся. Обитатели выходят из укрытий.',rain:'Начинается дождь. Обитатели ищут сухое место.',fog:'Туман сближает звуки и скрывает дальние тропы.'}[w],'weather',null,true);}
 setClimate(key,value){if(!['temperature','wind','rain'].includes(key)||!Number.isFinite(value))return;this.climate[key]=clamp(value,key==='temperature'?-5:0,key==='temperature'?35:1);if(key==='rain'){this.weatherMode='custom';this.weather=value>.02?'rain':'clear';}this.updateLight();for(const a of this.agents)a.decisionAt=this.elapsed;}
 autoClimate(){this.climate={temperature:null,wind:null,rain:null};this.setWeather('auto');this.updateLight();}
 shelterReason(a){if(this.rain>.4&&![5,6].includes(a.species))return 'пережидает дождь в сухом укрытии';if(this.wind>.72&&[0,2,7].includes(a.species))return 'ждёт, пока стихнет сильный ветер';if((this.temperature<8&&[2,7].includes(a.species))||this.temperature<2)return 'согревается в укрытии';return null;}
 feed(){if(this.paused||this.elapsed-this.lastFeed<12)return false;this.lastFeed=this.elapsed;for(const r of this.resources)if(r.kind!=='water')r.stock=1;for(const a of this.agents){a.stress*=.5;if(!['sleep','shelter'].includes(a.action)&&[0,1,2,3,4].includes(a.species)){const r=this.nearestResource(a,a.species===2?'flower':'seed');a.targetId=r.id;this.action(a,'seekFood','заметил свежие семена и цветы',r);}}this.ripples.push({x:.5,y:.55,born:this.elapsed});this.emit('На поляне появились семена и свежие цветы. Обитатели идут угощаться.','food',null,true);return true;}
 decide(a){const s=SPECIES[a.species],sleep=s.nocturnal?this.night<.62:this.night>.8;
  if(sleep){if(a.action==='sleep')return;if(dist(a,a.home)>.025){this.action(a,'goHome','хочет поспать в своём укрытии',a.home);return;}this.action(a,'sleep','восстанавливает силы до своего времени суток',null,15);return;}
  const shelter=this.shelterReason(a);if(shelter){if(a.action==='shelter'){a.reason=shelter;return;}this.action(a,'shelter',shelter,a.home,8);return;}
  const fox=(a.species===0||a.species===1||a.species===4)?this.agents.find(b=>b.species===5&&dist(a,b)<.085):null;
  if(fox&&a.action!=='flee'){a.stress=clamp(a.stress+.65);const dx=a.x-fox.x,dy=a.y-fox.y,d=Math.hypot(dx,dy)||.01;this.action(a,'flee','заметил лису и отходит подальше',{x:clamp(a.x+dx/d*.13,.16,.84),y:clamp(a.y+dy/d*.1,.3,.72)},6);this.sound(a,'alarm');this.emit(a.name+' предупреждает соседей о лисе.','alert',a.id);for(const b of this.agents)if(b.id!==a.id&&b.species!==5&&dist(a,b)<.13)b.stress=clamp(b.stress+.2);return;}
  if(a.energy<.25||(this.temperature>29&&a.energy<.62&&a.thirst<.7)){this.action(a,'rest',this.temperature>29?'пережидает жару в тени':'устал и восстанавливает силы',a.home,8);return;}
  if(a.thirst>.63&&a.species!==7){const r=this.nearestResource(a,'water');a.targetId=r.id;this.action(a,'seekWater','испытывает жажду и помнит ручей',r);return;}
  if((a.hunger>.52||a.species===2)&&a.species!==5&&a.species!==6&&a.species!==7){const r=this.nearestResource(a,a.species===2?'flower':'seed');a.targetId=r.id;this.action(a,'seekFood',a.species===2?'летит к цветам за нектаром':'проголодался и ищет семена',r);return;}
  if(a.species===1&&a.carrying){this.action(a,'cache','несёт семечко в свой тайник',a.home,5);return;}
  if(this.random()<a.sociability*.7){const peer=this.peer(a);if(peer){a.targetId=peer.id;this.action(a,'approach',(a.friends[peer.id]?'узнал знакомого':'заметил соседа')+' и хочет подойти',peer);return;}}
  if([0,3,4,6].includes(a.species)&&this.random()<.55){this.action(a,a.species===3?'peck':'sing',a.species===3?'ищет насекомых под корой':'подаёт голос и ждёт ответа',null,2);this.sound(a);this.emit(a.name+(a.species===3?' простукивает кору.':' зовёт соседей.'),'voice',a.id);const p=this.peer(a);if(p&&!this.pending.some(e=>e.id===p.id))this.pending.push({id:p.id,source:a.id,at:this.elapsed+1.2+this.random()});return;}
  if(a.species===7){const p=this.point(7);this.action(a,'wander','отвечает огонькам поблизости',p,5);return;}
  this.action(a,a.species===5?'patrol':'wander',a.species===5?'обходит знакомую территорию':'исследует знакомую поляну',this.point(a.species),4);
 }
 arrive(a){const r=this.resources.find(r=>r.id===a.targetId);switch(a.action){
  case 'seekFood':this.action(a,a.species===2?'pollinate':a.species===1?'gather':'eat',a.species===2?'собирает нектар и опыляет цветок':'нашёл еду',null,3+this.random()*4);a.targetId=r?.id;this.sound(a,a.species===2?'bee':'rustle');this.emit(a.name+(a.species===2?' нашла цветок с нектаром.':' нашёл семена на поляне.'),'food',a.id);break;
  case 'seekWater':this.action(a,'drink','утоляет жажду у ручья',null,3);this.sound(a,'water');this.emit(a.name+' пьёт у ручья.','water',a.id);break;
  case 'approach':{const peer=this.agents[a.targetId];if(peer&&dist(a,peer)<.09&&!['sleep','shelter','flee'].includes(peer.action)){a.friends[peer.id]=Math.min(20,(a.friends[peer.id]||0)+1);peer.friends[a.id]=Math.min(20,(peer.friends[a.id]||0)+1);a.stress*=.65;peer.stress*=.8;this.connections.push({from:a.id,to:peer.id,born:this.elapsed,type:'friend'});this.action(a,'social','встреча с '+peer.name,null,3);this.sound(a,'greeting');this.emit(a.name+' встречает '+peer.name+'.','social',a.id);peer.memory.unshift('Познакомился с '+a.name+'.');peer.memory.length=Math.min(3,peer.memory.length);}else this.action(a,'idle','сосед уже ушёл',null,1);break;}
  case 'goHome':this.action(a,'sleep','спит в своём укрытии',null,12);break;
  case 'cache':a.carrying=false;a.cacheCount++;this.action(a,'idle','оставил запас в тайнике',null,2);this.sound(a,'dig');this.emit(a.name+' прячет семечко. В тайнике: '+a.cacheCount+'.','food',a.id);break;
  case 'rest':case 'shelter':a.target=null;a.until=this.elapsed+7;break;
  default:this.action(a,'idle','осматривается на новом месте',null,1+this.random()*2);
 }}
 call(x=.5,y=.55){if(this.paused||this.elapsed-this.lastCall<5)return false;this.lastCall=this.elapsed;this.ripples.push({x,y,born:this.elapsed});const near=this.agents.filter(a=>!['sleep','shelter'].includes(a.action)&&dist(a,{x,y})<.28);for(const a of near){a.stress=clamp(a.stress+.2);a.signal=1;if([0,3,4,6].includes(a.species))this.pending.push({id:a.id,at:this.elapsed+.5+this.random()*2,source:null});else a.decisionAt=this.elapsed;}this.emit('По поляне прошёл шорох. Ближайшие обитатели прислушались.','world',null,true);return true;}
 tick(dt){if(this.paused||!Number.isFinite(dt)||dt<=0)return;dt=Math.min(dt,.25);this.elapsed+=dt;if(!this.holdTime)this.time=(this.time+dt*2*this.speed)%1440;this.updateLight();this.weatherAge+=dt;
  if(this.weatherMode==='auto'&&this.weatherAge>this.weatherDuration){const opts=this.weather==='clear'?['rain','fog']:['clear','clear',this.weather==='rain'?'fog':'rain'];this.changeWeather(opts[Math.floor(this.random()*opts.length)]);}
  const ease=1-Math.exp(-dt*.5);this.rain+=((this.climate.rain??(this.weather==='rain'?.76:0))-this.rain)*ease;this.fog+=((this.weather==='fog'?.72:.04)-this.fog)*ease;this.wind+=((this.climate.wind??(.15+this.rain*.45+Math.sin(this.elapsed*.04)*.1))-this.wind)*ease;
  for(const r of this.resources)r.stock=clamp(r.stock+dt*(r.kind==='water'?.1:.0018+this.rain*.001));
  for(let i=this.pending.length-1;i>=0;i--)if(this.pending[i].at<=this.elapsed){const e=this.pending.splice(i,1)[0],a=this.agents[e.id];if(!['sleep','shelter','flee','goHome'].includes(a.action)){this.sound(a);if(e.source!==null){this.connections.push({from:e.source,to:a.id,born:this.elapsed,type:'reply'});this.emit(a.name+' отвечает '+this.agents[e.source].name+'.','voice',a.id);}}}
  for(const a of this.agents){a.signal=Math.max(0,a.signal-dt*.9);a.stress=Math.max(0,a.stress-dt*.035);const resting=['sleep','rest','shelter'].includes(a.action);a.energy=clamp(a.energy+dt*(resting?.035:(a.target?-.003:.0007)));a.hunger=clamp(a.hunger+dt*(a.species===2?.002:.003));a.thirst=clamp(a.thirst+dt*.0025*(1+Math.max(0,this.temperature-22)*.12));
   const sleep=SPECIES[a.species].nocturnal?this.night<.62:this.night>.8;const rain=!!this.shelterReason(a);const needsInterrupt=(sleep&&!['sleep','goHome'].includes(a.action))||(rain&&!sleep&&a.action!=='shelter')||(!sleep&&!rain&&['sleep','shelter'].includes(a.action));
   if(needsInterrupt)this.decide(a);
   if(a.target){const dx=a.target.x-a.x,dy=a.target.y-a.y,d=Math.hypot(dx,dy);const step=SPECIES[a.species].pace*dt*(a.action==='flee'?1.7:1)*(1-this.fog*.25)*(1-this.wind*([0,2,3,4,6,7].includes(a.species)?.4:.1))*(this.temperature<10?.75:1);if(d<=step+.004){a.x=a.target.x;a.y=a.target.y;this.arrive(a);}else{a.x+=dx/d*step;a.y+=dy/d*step;a.step+=step;if([1,5].includes(a.species)&&a.step>.055){a.step=0;this.sound(a,'step');}}
   }else if(['eat','gather','pollinate'].includes(a.action)){const r=this.resources.find(r=>r.id===a.targetId);if(r&&r.stock>.01){r.stock=Math.max(0,r.stock-dt*.008);a.hunger=Math.max(0,a.hunger-dt*.12);a.energy=clamp(a.energy+dt*.02);if(a.action==='pollinate'){a.visits++;r.stock=clamp(r.stock+dt*.003);}}if(a.action==='gather'&&a.hunger<.35)a.carrying=true;
   }else if(a.action==='drink')a.thirst=Math.max(0,a.thirst-dt*.25);
   if(!a.target&&this.elapsed>a.until&&this.elapsed>a.decisionAt)this.decide(a);
  }
  this.connections=this.connections.filter(c=>this.elapsed-c.born<3.5);this.ripples=this.ripples.filter(r=>this.elapsed-r.born<3);this.activity=this.agents.filter(a=>!['sleep','rest','idle','shelter'].includes(a.action)).length/this.agents.length;this.tension=this.agents.reduce((v,a)=>v+a.stress,0)/this.agents.length;this.bees=this.agents.filter(a=>a.species===2&&a.action!=='sleep'&&a.action!=='shelter').length/18;
 }
 drain(){return this.outbox.splice(0);}
 snapshot(){return{version:3,climate:{...this.climate},holdTime:this.holdTime,seed:this.seed,time:this.time,speed:this.speed,weatherMode:this.weatherMode,weather:this.weather,selectedId:this.selectedId,agents:this.agents.map(a=>({id:a.id,species:a.species,x:a.x,y:a.y,energy:a.energy,hunger:a.hunger,thirst:a.thirst,stress:a.stress,friends:a.friends,memory:a.memory,cacheCount:a.cacheCount}))};}
 get awake(){return this.agents.filter(a=>a.action!=='sleep').length;}
 get selected(){return this.agents[this.selectedId]||this.agents[0];}
}
