import {Ecosystem,formatClock,SPECIES,ACTIONS} from './ecosystem.js?v=3';
import {ForestAudio} from './audio.js?v=14';
import {LifeRenderer} from './life-renderer.js?v=8';
const $=id=>document.getElementById(id),STORAGE='forest-world-v1',speeds=[.5,1,2,4];let saved=null;try{saved=JSON.parse(localStorage.getItem(STORAGE));}catch{}
const mixDefaults={volume:50,music:72,'world-volume':65,water:35,leaves:50,calls:24,softness:92,intimacy:85,detail:30};
const presets={close:{name:'Тихое погружение',waterMode:2,hour:18.5,temperature:22,wind:2.5,rain:.08,mix:{music:24,'world-volume':82,water:36,leaves:78,calls:12,softness:96,intimacy:95,detail:30}},warm:{name:'Тёплая поляна',waterMode:0,hour:9,temperature:23,wind:1.5,rain:0,mix:{music:74,'world-volume':66,water:35,leaves:50,calls:20,softness:90,detail:22}},rain:{name:'Дождь и воздух',waterMode:0,hour:17,temperature:17,wind:2.5,rain:.62,mix:{music:65,'world-volume':82,water:55,leaves:25,calls:8,softness:93,detail:18}},night:{name:'Ночь у ручья',waterMode:2,hour:23,temperature:16,wind:1,rain:0,mix:{music:45,'world-volume':72,water:24,leaves:35,calls:12,softness:95,detail:10}},nature:{name:'Только природа',waterMode:0,hour:9,temperature:22,wind:3,rain:0,mix:{music:0,'world-volume':80,water:40,leaves:68,calls:30,softness:85,detail:35}}};
let currentPreset=saved?.radioVersion===3&&presets[saved.preset]?saved.preset:'custom',radioMode=saved?.radioMode??true,lastAudioTime=0;
const world=new Ecosystem(saved?.world),renderer=new LifeRenderer($('world'),world);let enabled=false,busy=false,last=0,lastUi=0,lastSave=0,lastEvent=0;
const audio=new ForestAudio((running,error)=>{enabled=running;updateSound();if(error)$('audio-note').textContent=error;});
function bounded(value,fallback){return Number.isFinite(value)?Math.max(0,Math.min(100,value)):fallback;}
for(const [id,fallback]of Object.entries(mixDefaults))$(id).value=bounded(saved?.mix?.[id],fallback);$('sleep-timer').value=[0,15,30,60,120].includes(saved?.sleepMinutes)?saved.sleepMinutes:0;
const savedWaterMode=saved?.waterMode;$('water-mode').value=Number.isInteger(savedWaterMode)&&savedWaterMode>=0&&savedWaterMode<=4?savedWaterMode:(presets[saved?.preset]?.waterMode??0);
if(saved?.soundVersion!==6)$('water').value=presets[saved?.preset]?.mix.water??35;
function save(){try{localStorage.setItem(STORAGE,JSON.stringify({soundVersion:6,waterMode:Number($('water-mode').value),radioVersion:3,world:world.snapshot(),mix:Object.fromEntries(Object.keys(mixDefaults).map(id=>[id,Number($(id).value)])),preset:currentPreset,radioMode,sleepMinutes:Number($('sleep-timer').value)}));}catch{}}
function fillRange(el){el.style.setProperty('--fill',((el.value-el.min)/(el.max-el.min)*100)+'%');}
function updateSound(){$('listen').setAttribute('aria-pressed',String(enabled));$('listen-text').textContent=enabled?'Выключить радио':audio.enabled?'Продолжить слушать':'Включить радио';$('audio-note').textContent=audio.finished?'Таймер завершён. Лес тихо попрощался.':enabled?'Можно просто слушать. Атмосфера будет меняться плавно.':world.paused?'Мир замер. Нажми «Продолжить», чтобы он ожил.':'Выбери атмосферу и включи радио. Начни с небольшой громкости.';}
function updateMix(){for(const id of Object.keys(mixDefaults)){$(id+'-value').textContent=$(id).value+'%';fillRange($(id));}audio.setVolume(Number($('volume').value)/100);audio.setMix(Number($('music').value)/100,Number($('world-volume').value)/100);audio.setTexture({waterMode:Number($('water-mode').value),...Object.fromEntries(['water','leaves','calls','detail','softness','intimacy'].map(id=>[id,Number($(id).value)/100]))});}
function presetUi(){$('preset-name').textContent=presets[currentPreset]?.name||'Своя атмосфера';document.querySelectorAll('[data-preset]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.preset===currentPreset)));}
function custom(){currentPreset='custom';presetUi();}
function setRadioMode(value){radioMode=!!value;document.body.classList.toggle('radio-mode',radioMode);$('radio-mode').setAttribute('aria-pressed',String(radioMode));$('radio-mode').textContent=radioMode?'Наблюдать за жизнью':'Только слушать';}
function climateUi(){const values={temperature:Math.round(world.temperature),wind:Math.round((world.climate.wind??world.wind)*24)/2,'rain-level':Math.round((world.climate.rain??world.rain)*100)};for(const [id,value]of Object.entries(values)){$(id).value=value;$(id+'-value').textContent=value+(id==='temperature'?' °C':id==='wind'?' м/с':'%');fillRange($(id));}$('hold-time').checked=world.holdTime;$('climate-effect').textContent=world.temperature<8?'В прохладе пчёлы греются в укрытиях. Жизнь становится тише.':world.wind>.72?'Сильный ветер: птицы и пчёлы держатся ближе к укрытиям.':world.temperature>29?'В жару обитатели чаще пьют и отдыхают в тени.':world.rain>.4?'Дождь наполняет поляну. Обитатели пережидают его под укрытием.':'Мягкая погода: обитатели гуляют, ищут еду и встречаются.';}
function applyPreset(key,persist=true){const p=presets[key];if(!p)return;currentPreset=key;$('water-mode').value=p.waterMode;for(const [id,value]of Object.entries(p.mix))$(id).value=value;world.setTime(p.hour);world.holdTime=true;world.setWeather(p.rain?'rain':'clear');world.setClimate('temperature',p.temperature);world.setClimate('wind',p.wind/12);world.setClimate('rain',p.rain);updateMix();audio.setEnvironment(world);presetUi();updateUi();if(persist)save();}
function setSpeed(index){world.speed=speeds[index];$('speed').value=index;$('speed-value').textContent=['Медленный','Обычный','Быстрый','Очень быстрый'][index];fillRange($('speed'));save();}
function selectAgent(id){if(!Number.isInteger(id)||!world.agents[id])return;world.selectedId=id;setRadioMode(false);$('agent-select').value=id;updateInspector();save();}
function updateInspector(){const a=world.selected,s=SPECIES[a.species];$('agent-glyph').textContent=s.glyph;$('agent-glyph').style.color=s.color;$('agent-action').textContent=ACTIONS[a.action].charAt(0).toUpperCase()+ACTIONS[a.action].slice(1);$('agent-reason').textContent=a.reason+'.';for(const [id,value]of [['need-food',1-a.hunger],['need-energy',a.energy],['need-calm',1-a.stress]]){$(id).value=value;$(id).textContent=Math.round(value*100)+'%';$(id).setAttribute('aria-valuetext',Math.round(value*100)+'%');}const friends=Object.keys(a.friends).length;const memory=a.memory[0]||'Изучает поляну и запоминает соседей.';$('agent-memory').textContent=memory+(friends?' Знакомых: '+friends+'.':'')+(a.cacheCount?' Запасов: '+a.cacheCount+'.':'');}
function updateUi(){
 $('clock').textContent=formatClock(world.time);$('period').textContent=world.period;$('awake-count').textContent=world.awake;$('population').textContent=world.agents.length;$('activity').textContent=Math.round((world.activity||0)*100)+'%';$('tension').textContent=Math.round((world.tension||0)*100)+'%';
 const dark=world.night>.72,rain=world.rain>.3,fog=world.fog>.35;$('scene-label').textContent=world.paused?'Мир на паузе':rain?'Обитатели ищут укрытие':dark?'Ночная жизнь':world.tension>.08?'Соседи насторожились':'Жизнь продолжается';
 $('world-summary').textContent=world.paused?'Все дела подождут. Можно рассмотреть любой момент.':rain?'Обитатели укрываются от дождя. Капли и мягкий шелест заполняют поляну.':dark?'Дневные обитатели спят. Совы обходят владения, светлячки перекликаются огоньками.':fog?'Туман скрывает дальние тропы. Обитатели движутся медленнее и держатся ближе.':'Кто-то ищет семена, кто-то спешит к ручью. Встречи и маленькие события складываются в музыку.';
 $('weather-description').textContent=(rain?'Дождь':fog?'Туман':dark?'Ясная ночь':'Ясно')+' · '+Math.round(world.temperature)+'°';$('weather-symbol').textContent=rain?'☂':fog?'≋':dark?'☾':'☀';$('time-flow').textContent=world.paused?'на паузе':world.holdTime?'время закреплено':'день идёт сам';$('weather-mode-label').textContent=world.weatherMode==='auto'?'меняется сама':'твой выбор';document.body.classList.toggle('is-night',world.night>.58);document.body.classList.toggle('is-paused',world.paused);document.documentElement.style.setProperty('--night',String(world.night));
 document.querySelectorAll('[data-time]').forEach(b=>{const periods={'6.3':'Рассвет','12':'День','18.5':'Закат','23':'Ночь'},active=periods[b.dataset.time]===world.period;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});document.querySelectorAll('[data-weather]').forEach(b=>{const active=b.dataset.weather===world.weatherMode;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});
 if(lastEvent!==world.eventId){lastEvent=world.eventId;const fragment=document.createDocumentFragment();for(const e of world.events.slice(0,5)){const li=document.createElement('li'),time=document.createElement('time'),text=document.createElement('span');time.textContent=formatClock(e.time);text.textContent=e.text;li.append(time,text);if(e.agentId!==null){li.tabIndex=0;li.setAttribute('role','button');li.setAttribute('aria-label','Наблюдать: '+e.text);li.addEventListener('click',()=>selectAgent(e.agentId));li.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();selectAgent(e.agentId);}});}fragment.append(li);}$('events').replaceChildren(fragment);}updateInspector();climateUi();
}
function chooseTime(hour){custom();world.setTime(hour);audio.clear();audio.setEnvironment(world);updateUi();save();}
function chooseWeather(weather){custom();world.setWeather(weather);updateUi();save();}
async function pause(paused){world.paused=paused;$('pause').setAttribute('aria-pressed',String(paused));$('pause').querySelector('span').textContent=paused?'Продолжить':'Замереть';$('pause').querySelector('path').setAttribute('d',paused?'m8 5 10 7-10 7V5Z':'M8 5v14M16 5v14');await audio.setPaused(paused);updateUi();updateSound();}
async function startListening(){if(world.paused)await pause(false);audio.setEnvironment(world);await audio.enable();}
$('listen').addEventListener('click',async()=>{if(busy)return;busy=true;$('listen').disabled=true;try{if(enabled)await audio.disable();else await startListening();}catch(error){$('audio-note').textContent=error.message||'Не удалось включить звук. Нажми ещё раз.';}finally{busy=false;$('listen').disabled=false;}});
$('pause').addEventListener('click',()=>void pause(!world.paused));for(const id of Object.keys(mixDefaults))$(id).addEventListener('input',()=>{if(id!=='volume')custom();updateMix();save();});$('speed').addEventListener('input',()=>setSpeed(Number($('speed').value)));
document.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>chooseTime(Number(b.dataset.time))));document.querySelectorAll('[data-weather]').forEach(b=>b.addEventListener('click',()=>chooseWeather(b.dataset.weather)));
document.querySelectorAll('[data-preset]').forEach(button=>button.addEventListener('click',()=>applyPreset(button.dataset.preset)));
$('radio-mode').addEventListener('click',()=>{setRadioMode(!radioMode);save();});
$('hold-time').addEventListener('change',()=>{world.holdTime=$('hold-time').checked;updateUi();save();});
for(const [id,key,divisor]of [['temperature','temperature',1],['wind','wind',12],['rain-level','rain',100]])$(id).addEventListener('input',()=>{custom();world.setClimate(key,Number($(id).value)/divisor);climateUi();audio.setEnvironment(world);save();});
$('auto-climate').addEventListener('click',()=>{custom();world.autoClimate();updateUi();save();});
$('water-mode').addEventListener('change',()=>{custom();updateMix();save();});
$('sleep-timer').addEventListener('change',()=>{audio.setSleep(Number($('sleep-timer').value));$('timer-left').textContent=audio.sleepMinutes?'плавное затихание':'';save();});
$('feed-world').addEventListener('click',()=>{$('interaction-note').textContent=world.feed()?'Угощение на поляне. Соседи идут к семенам и цветам.':world.paused?'Сначала продолжи жизнь мира.':'Обитатели ещё заняты угощением. Подожди немного.';updateUi();save();});
audio.onHeartbeat=message=>{const dt=lastAudioTime?Math.min(5,Math.max(0,message.time-lastAudioTime)):1;lastAudioTime=message.time;if(document.hidden&&audio.enabled&&!world.paused){for(let remaining=dt;remaining>.0001;remaining-=.2)world.tick(Math.min(.2,remaining));for(const event of world.drain())audio.song(event);audio.setEnvironment(world);if(performance.now()-lastSave>8000){save();lastSave=performance.now();}}$('timer-left').textContent=message.remaining>0?Math.ceil(message.remaining/60)+' мин осталось':'';};
audio.onSleep=()=>{$('timer-left').textContent='Готово';updateSound();save();};
try{if(navigator.mediaSession){if(window.MediaMetadata)navigator.mediaSession.metadata=new MediaMetadata({title:'Лес внутри',artist:'Тихое радио',album:'Мир, который живёт'});navigator.mediaSession.setActionHandler('play',()=>{void startListening().catch(error=>{$('audio-note').textContent=error.message;});});navigator.mediaSession.setActionHandler('pause',()=>{void audio.disable();});navigator.mediaSession.setActionHandler('stop',()=>{void audio.disable();});}}catch{}
$('call-birds').addEventListener('click',()=>{world.call();updateUi();});$('connections').addEventListener('click',()=>{renderer.showConnections=!renderer.showConnections;$('connections').setAttribute('aria-pressed',String(renderer.showConnections));$('connections').textContent=renderer.showConnections?'Связи видны':'Показать связи';});
$('world').addEventListener('pointerup',e=>{const p=renderer.pointer(e.clientX,e.clientY);const nearest=world.agents.filter(a=>a.action!=='sleep'||a.species!==7).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(nearest)selectAgent(nearest.id);});$('agent-select').addEventListener('change',()=>selectAgent(Number($('agent-select').value)));
for(let i=0;i<SPECIES.length;i++){const s=SPECIES[i],group=document.createElement('optgroup');group.label=s.plural;for(const a of world.agents.filter(a=>a.species===i)){const option=document.createElement('option');option.value=a.id;option.textContent=a.name;group.append(option);}$('agent-select').append(group);const item=document.createElement('span'),glyph=document.createElement('i');glyph.textContent=s.glyph;glyph.style.color=s.color;item.append(glyph,document.createTextNode(s.plural+' '+s.count));$('species-legend').append(item);}
$('agent-select').value=world.selectedId;
$('about-toggle').addEventListener('click',()=>{const expanded=$('about-toggle').getAttribute('aria-expanded')!=='true';$('about-toggle').setAttribute('aria-expanded',String(expanded));$('about').hidden=!expanded;$('about-toggle').querySelector('span').textContent=expanded?'−':'+';});
document.addEventListener('visibilitychange',()=>{last=0;save();void audio.setHidden(document.hidden);});window.addEventListener('pagehide',()=>{save();void audio.disable();});renderer.ready.then(()=>{$('scene-loading').hidden=true;renderer.render();}).catch(()=>{$('scene-loading').textContent='Не удалось загрузить поляну. Обнови страницу.';});
function frame(t){if(!document.hidden){const dt=last?Math.min((t-last)/1000,.1):0;world.tick(dt);for(const event of world.drain())audio.song(event);renderer.render();if(t-lastUi>250){updateUi();audio.setEnvironment(world);lastUi=t;}if(t-lastSave>8000){save();lastSave=t;}}last=t;requestAnimationFrame(frame);}
if(saved?.radioVersion!==3)applyPreset('warm',false);setRadioMode(radioMode);presetUi();updateMix();audio.setSleep(Number($('sleep-timer').value));setSpeed(Math.max(0,speeds.indexOf(world.speed)));updateUi();updateSound();requestAnimationFrame(frame);
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{void Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};const state=()=>({time:formatClock(world.time),weather:world.weather,weatherMode:world.weatherMode,temperature:world.temperature,wind:world.wind*12,rain:world.rain,holdTime:world.holdTime,preset:currentPreset,paused:world.paused,agents:world.agents.length,selected:{id:world.selected.id,name:world.selected.name,action:world.selected.action,reason:world.selected.reason},music:Number($('music').value),worldVolume:Number($('world-volume').value)});
 register({name:'read_forest',description:'Read ecosystem state and the currently observed agent.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>state()});
 register({name:'configure_forest',description:'Set the visible time, weather or selected agent without starting sound.',inputSchema:{type:'object',properties:{hour:{type:'number',minimum:0,maximum:23.99},weather:{type:'string',enum:['auto','clear','rain','fog']},agentId:{type:'integer',minimum:0,maximum:67}},additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['hour','weather','agentId'].includes(k)))throw new Error('Invalid input');if(input.hour!==undefined&&(!Number.isFinite(input.hour)||input.hour<0||input.hour>=24))throw new Error('Invalid hour');if(input.weather!==undefined&&!['auto','clear','rain','fog'].includes(input.weather))throw new Error('Invalid weather');if(input.agentId!==undefined&&(!Number.isInteger(input.agentId)||!world.agents[input.agentId]))throw new Error('Invalid agent');if(input.hour!==undefined)chooseTime(input.hour);if(input.weather!==undefined)chooseWeather(input.weather);if(input.agentId!==undefined)selectAgent(input.agentId);return state();}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
