import {MaldivesWorld,ACTIVITIES} from './maldives-world.js?v=15';
import {MaldivesRenderer} from './maldives-renderer.js?v=15';
import {MaldivesAudio} from './maldives-audio.js?v=15';
const $=id=>document.getElementById(id),STORAGE='quiet-maldives-v1',defaults={volume:50,music:34,'world-volume':85,ocean:65,'rain-volume':65,details:40,softness:96},speeds=[.5,1,2,4];
let saved={};try{saved=JSON.parse(localStorage.getItem(STORAGE))||{};}catch{}
const world=new MaldivesWorld(saved.world||{}),renderer=new MaldivesRenderer($('world'),world);let running=false,busy=false,radioMode=!!saved.radioMode,last=0,lastUI=0,lastPaint=0,lastSave=0,lastEvent=-1,lastAudioTime=0,lastFocus=world.focus;
const audio=new MaldivesAudio((active,error)=>{running=active;updateSound();if(error)$('audio-note').textContent=error;});
const clock=t=>String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0');
for(const [id,value]of Object.entries(defaults))$(id).value=Number.isFinite(saved.mix?.[id])?Math.max(0,Math.min(100,saved.mix[id])):value;
$('sleep-timer').value=[0,15,30,60,120].includes(saved.sleepMinutes)?saved.sleepMinutes:0;
function fill(el){el.style.setProperty('--fill',((Number(el.value)-Number(el.min))/(Number(el.max)-Number(el.min))*100)+'%');}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify({world:world.snapshot(),mix:Object.fromEntries(Object.keys(defaults).map(id=>[id,Number($(id).value)])),sleepMinutes:Number($('sleep-timer').value),radioMode}));}catch{}}
function updateSound(){$('listen').setAttribute('aria-pressed',String(running));$('listen-text').textContent=running?'Выключить звук':audio.enabled?'Продолжить слушать':'Слушать Мальдивы';$('audio-note').textContent=audio.finished?'Таймер завершён. Пусть отдых продолжается во сне.':running?'Океан, мягкая музыка и маленькая жизнь рядом. Можно просто слушать.':world.paused?'Остров замер. Нажми «Продолжить».':'Тёплый океан и музыка без спешки. Нажми «Слушать Мальдивы».';}
function syncSound(){audio.setVolume(Number($('volume').value)/100);audio.setMix(Number($('music').value)/100,Number($('world-volume').value)/100);audio.setTexture({ocean:Number($('ocean').value)/100,rainVolume:Number($('rain-volume').value)/100,details:Number($('details').value)/100,softness:Number($('softness').value)/100,leaves:.28,inside:world.activity.indoor?1:0});audio.setScene(world.focus);audio.setEnvironment(world);}
function mixUI(){for(const id of Object.keys(defaults)){$(id+'-value').textContent=$(id).value+'%';fill($(id));}syncSound();}
function activityUI(){for(const button of document.querySelectorAll('[data-activity]'))button.setAttribute('aria-pressed',String(button.dataset.activity===world.focus));$('focus-description').textContent=world.activity.description;$('activity-name').textContent=world.activity.name;$('tour').setAttribute('aria-pressed',String(world.tour));$('tour').textContent=world.tour?'Прогулка идёт · остановить':'День отпуска';}
function applyAmbience(){const a=world.activity;$('music').value=Math.round(a.music*100);$('ocean').value=Math.round(a.ocean*100);$('details').value=['suite','dive'].includes(a.id)?28:40;world.setTime(a.hour);mixUI();activityUI();lastFocus=world.focus;}
function chooseActivity(id){world.chooseActivity(id);applyAmbience();$('interaction-note').textContent='Гости выбирают занятие и постепенно собираются вместе.';updateUI();save();}
function select(id){if(!Number.isInteger(id)||!world.agents[id])return;world.selectedId=id;$('agent-select').value=id;setRadio(false);inspect();renderer.render();save();}
function inspect(){const a=world.selected;$('agent-glyph').textContent=a.kind==='human'?'◉':a.kind==='turtle'?'◌':a.kind==='dolphin'?'≈':'⋈';$('agent-glyph').style.color=a.color;$('agent-action').textContent=a.name+' '+a.action+'.';$('agent-reason').textContent=a.role+' · '+(a.kind==='human'?'на острове есть время для себя':'жизнь тёплой лагуны');for(const [id,v]of [['need-food',1-a.hunger],['need-energy',a.energy],['need-comfort',a.comfort]]){$(id).value=v;$(id).setAttribute('aria-valuetext',Math.round(v*100)+'%');}$('agent-memory').textContent=a.memory;}
function climateUI(){for(const [id,value,unit]of [['temperature',world.temperature,' °C'],['wind',Math.round(world.wind*24)/2,' м/с'],['rain-level',Math.round(world.rain*100),'%'],['candles',Math.round(world.candles*100),'%']]){if(document.activeElement!==$(id))$(id).value=value;$(id+'-value').textContent=value+unit;fill($(id));}$('hold-time').checked=world.holdTime;$('climate-effect').textContent=world.badWeather?(world.rain>.55?'Гости выбирают чай, спа и уютные комнаты. Над лагуной идёт тёплый дождь.':'Ветер усилился. Гости отдыхают в спа и уютных бунгало.'):world.temperature>31?'Полуденное тепло: в тени пальм и под водой особенно приятно.':'Лагуна спокойна. Гости гуляют по пляжу и отправляются к рифу.';}
function updateUI(){
 $('clock').textContent=clock(world.time);$('period').textContent=world.period;$('awake-count').textContent=world.awake;$('scene-label').textContent=world.paused?'Остров на паузе':world.rain>.1?'Тёплый дождь над островом':world.period==='Ночь'?'Остров засыпает':'У каждого свой маленький отпуск';$('time-flow').textContent=world.holdTime?'время закреплено':'время идёт';$('weather-symbol').textContent=world.rain>.1?'☂':world.night>.7?'☾':'☀';$('weather-description').textContent=(world.rain>.1?'Дождь':world.weather==='cloud'?'Облачно':'Ясно')+' · '+Math.round(world.temperature)+'°';$('world-summary').textContent=world.period==='Ночь'?'В бунгало загораются лампы. У рифа медленно плывут рыбы.':world.badWeather?'В комнатах уютно. Повар ставит чайник, а гости выбирают отдых под крышей.':'Повар готовит, гости выбирают отдых, гид ждёт у лагуны. Остров живёт в своём ритме.';
 document.querySelectorAll('[data-time]').forEach(b=>{const p={7:'Утро',13:'День',18:'Вечер',1:'Ночь'},active=p[b.dataset.time]===world.period;b.setAttribute('aria-pressed',String(active));b.classList.toggle('selected',active);});document.querySelectorAll('[data-weather]').forEach(b=>{const active=b.dataset.weather===world.weather;b.setAttribute('aria-pressed',String(active));b.classList.toggle('selected',active);});
 if(lastEvent!==world.eventId){lastEvent=world.eventId;const fragment=document.createDocumentFragment();for(const e of world.events.slice(0,5)){const li=document.createElement('li'),time=document.createElement('time'),text=document.createElement('span');time.textContent=clock(e.time);text.textContent=e.text;li.append(time,text);if(e.agent!==null){li.tabIndex=0;li.setAttribute('role','button');li.addEventListener('click',()=>select(e.agent));li.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();select(e.agent);}});}fragment.append(li);}$('events').replaceChildren(fragment);}
 $('world').setAttribute('aria-label','Миниатюрный остров Мальдивы: '+world.period.toLowerCase()+', '+(world.rain>.1?'дождь':'спокойная погода')+'. '+world.activity.name+'. Выбери жителя на карте или в списке.');climateUI();inspect();
}
function setRadio(value){radioMode=!!value;document.body.classList.toggle('radio-mode',radioMode);$('radio-mode').setAttribute('aria-pressed',String(radioMode));$('radio-mode').textContent=radioMode?'Наблюдать за жизнью':'Только слушать';}
async function pause(value){world.paused=value;$('pause').textContent=value?'Продолжить':'Замереть';$('pause').setAttribute('aria-pressed',String(value));await audio.setPaused(value);updateUI();updateSound();}
async function start(){if(world.paused)await pause(false);syncSound();await audio.enable();}
$('listen').addEventListener('click',async()=>{if(busy)return;busy=true;$('listen').disabled=true;try{if(running)await audio.disable();else await start();}catch(e){$('audio-note').textContent=e.message||'Не удалось включить звук. Нажми ещё раз.';}finally{busy=false;$('listen').disabled=false;}});
$('pause').addEventListener('click',()=>void pause(!world.paused));$('radio-mode').addEventListener('click',()=>{setRadio(!radioMode);save();});
for(const id of Object.keys(defaults))$(id).addEventListener('input',()=>{mixUI();save();});
for(const [id,key,div]of [['temperature','temperature',1],['wind','wind',12],['rain-level','rain',100],['candles','candles',100]])$(id).addEventListener('input',()=>{world[key]=Number($(id).value)/div;if(key==='rain')world.weather=world.rain>0?'rain':'clear';climateUI();updateUI();syncSound();save();});
document.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>{world.setTime(Number(b.dataset.time));updateUI();syncSound();save();}));document.querySelectorAll('[data-weather]').forEach(b=>b.addEventListener('click',()=>{world.setWeather(b.dataset.weather);updateUI();syncSound();save();}));
$('hold-time').addEventListener('change',()=>{world.holdTime=$('hold-time').checked;updateUI();save();});$('sleep-timer').addEventListener('change',()=>{audio.setSleep(Number($('sleep-timer').value));$('timer-left').textContent=audio.sleepMinutes?'плавное затихание':'';save();});
$('speed').value=Math.max(0,speeds.indexOf(world.speed));function speedUI(){$('speed-value').textContent=['Медленный','Обычный','Быстрый','Очень быстрый'][Number($('speed').value)];fill($('speed'));}$('speed').addEventListener('input',()=>{world.speed=speeds[Number($('speed').value)];speedUI();save();});
for(const a of ACTIVITIES){const b=document.createElement('button');b.dataset.activity=a.id;b.setAttribute('aria-pressed',String(world.focus===a.id));const icon=document.createElement('span'),name=document.createElement('span');icon.className='activity-icon';icon.textContent=a.icon;icon.setAttribute('aria-hidden','true');name.textContent=a.name;b.append(icon,name);b.addEventListener('click',()=>chooseActivity(a.id));$('activities').append(b);}
for(const group of ['Гости и команда','Обитатели лагуны']){const g=document.createElement('optgroup');g.label=group;for(const a of world.agents.filter(a=>(a.kind==='human')===(group==='Гости и команда'))){const option=document.createElement('option');option.value=a.id;option.textContent=a.name+' · '+a.role;g.append(option);}$('agent-select').append(g);}$('agent-select').value=world.selectedId;$('agent-select').addEventListener('change',()=>select(Number($('agent-select').value)));
$('world').addEventListener('pointerup',e=>{const hit=renderer.hit(e.clientX,e.clientY);if(hit.agent!==undefined)select(hit.agent);else if(hit.activity)chooseActivity(hit.activity);});$('paths').addEventListener('click',()=>{renderer.showPaths=!renderer.showPaths;$('paths').setAttribute('aria-pressed',String(renderer.showPaths));$('paths').textContent=renderer.showPaths?'Пути видны':'Показать пути';renderer.render();});
$('tea').addEventListener('click',()=>{$('interaction-note').textContent=world.service()?'Нура принесёт чай и фрукты. Можно устроиться поудобнее.':world.paused?'Сначала продолжи жизнь острова.':'Чай уже готовят. Скоро всё будет.';updateUI();});$('invite').addEventListener('click',()=>{$('interaction-note').textContent=world.invite()?'Друзья идут к тебе. Вместе ещё уютнее.':'Сначала продолжи жизнь острова.';updateUI();});$('tour').addEventListener('click',()=>{world.tour=!world.tour;world.nextTour=world.elapsed+120;activityUI();$('interaction-note').textContent=world.tour?'Каждые две минуты — следующее занятие, новое время суток и своя музыка.':'Можно остаться здесь сколько захочется.';save();});
$('about-toggle').addEventListener('click',()=>{const open=$('about').hidden;$('about').hidden=!open;$('about-toggle').setAttribute('aria-expanded',String(open));});
function advance(dt){for(let t=0;t<dt;t+=.1)world.tick(Math.min(.1,dt-t));if(world.focus!==lastFocus){applyAmbience();save();}for(const e of world.drain())audio.song(e);}
audio.onHeartbeat=m=>{const dt=lastAudioTime?Math.min(5,Math.max(0,m.time-lastAudioTime)):1;lastAudioTime=m.time;if(document.hidden&&audio.enabled&&!world.paused){advance(dt);syncSound();}$('timer-left').textContent=m.remaining>0?Math.ceil(m.remaining/60)+' мин осталось':'';};audio.onSleep=()=>{$('timer-left').textContent='Готово';updateSound();};
try{if(navigator.mediaSession){if(window.MediaMetadata)navigator.mediaSession.metadata=new MediaMetadata({title:'Мальдивы',artist:'Тихие миры',album:'Океан и маленький отпуск'});navigator.mediaSession.setActionHandler('play',()=>void start().catch(e=>{$('audio-note').textContent=e.message;}));navigator.mediaSession.setActionHandler('pause',()=>void audio.disable());navigator.mediaSession.setActionHandler('stop',()=>void audio.disable());}}catch{}
document.addEventListener('visibilitychange',()=>{last=0;save();void audio.setHidden(document.hidden);});window.addEventListener('pagehide',()=>{save();void audio.disable();});renderer.ready.then(()=>{$('scene-loading').hidden=true;renderer.render();}).catch(()=>{$('scene-loading').textContent='Не удалось загрузить остров. Обнови страницу.';});
function frame(t){if(!document.hidden){const dt=last?Math.min(.1,(t-last)/1000):0;advance(dt);if(t-lastPaint>(renderer.reduced?250:radioMode?66:33)){renderer.render();lastPaint=t;}if(t-lastUI>350){updateUI();syncSound();lastUI=t;}if(t-lastSave>8000){save();lastSave=t;}}last=t;requestAnimationFrame(frame);}
setRadio(radioMode);mixUI();activityUI();speedUI();updateUI();audio.setSleep(Number($('sleep-timer').value));requestAnimationFrame(frame);
