import {SPECIES} from './engine.js';
export class ForestRenderer {
  constructor(canvas,forest){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.forest=forest;this.image=new Image();this.image.src=new URL('./assets/forest.webp',import.meta.url);this.ready=this.image.decode();this.width=0;this.height=0;this.dpr=Math.min(window.devicePixelRatio||1,1.75);this.reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas);this.resize();this.lastNight=0;}
  resize(){const b=this.canvas.getBoundingClientRect();this.width=b.width;this.height=b.height;this.canvas.width=Math.round(b.width*this.dpr);this.canvas.height=Math.round(b.height*this.dpr);this.ctx.setTransform(this.dpr,0,0,this.dpr,0,0);this.size=Math.min(this.width,this.height)*.98;this.ox=(this.width-this.size)/2;this.oy=(this.height-this.size)/2-5;}
  position(x,y){return{x:this.ox+x*this.size,y:this.oy+y*this.size};}
  pointer(clientX,clientY){const r=this.canvas.getBoundingClientRect();return{x:Math.max(.12,Math.min(.88,(clientX-r.left-this.ox)/this.size)),y:Math.max(.25,Math.min(.79,(clientY-r.top-this.oy)/this.size))};}
  render(){const c=this.ctx,f=this.forest,w=this.width,h=this.height;if(!w||!this.image.complete||!this.image.naturalWidth)return;c.clearRect(0,0,w,h);c.fillStyle='#f4f5ed';c.fillRect(0,0,w,h);c.drawImage(this.image,this.ox,this.oy,this.size,this.size);
    // One scene state drives light, inhabitants, weather and sound.
    this.lastNight+=(f.night-this.lastNight)*.035;const n=this.lastNight;c.fillStyle=`rgba(13,31,41,${n*.74+f.rain*.07})`;c.fillRect(0,0,w,h);
    if(f.dawn>.1||f.dusk>.1){const g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,`rgba(255,218,143,${(f.dawn*.15+f.dusk*.21)*(1-f.rain)})`);g.addColorStop(1,'rgba(255,218,143,0)');c.fillStyle=g;c.fillRect(0,0,w,h);}
    this.drawWater();
    for(const b of [...f.birds].sort((a,b)=>a.y-b.y))this.drawBird(b);
    if(n>.15)this.drawFireflies(n);
    this.drawAtmosphere();
    for(const ripple of f.ripples){const age=f.elapsed-ripple.born,p=this.position(ripple.x,ripple.y);c.strokeStyle=`rgba(223,237,173,${Math.max(0,1-age/2.5)*.8})`;c.lineWidth=1.8;c.beginPath();c.ellipse(p.x,p.y,8+age*29,4+age*13,0,0,Math.PI*2);c.stroke();}
  }
  drawWater(){const c=this.ctx,f=this.forest,p=this.position(.737,.616);c.save();c.beginPath();c.ellipse(p.x,p.y,this.size*.069,this.size*.036,-.3,0,Math.PI*2);c.clip();for(let i=0;i<5;i++){const phase=(f.elapsed*.14+i*.23)%1;c.strokeStyle=`rgba(199,237,221,${(1-phase)*.25})`;c.lineWidth=1;c.beginPath();c.ellipse(p.x+Math.sin(i)*this.size*.03,p.y+Math.cos(i)*this.size*.015,phase*this.size*.055,phase*this.size*.027,-.3,0,Math.PI*2);c.stroke();}c.restore();}
  drawBird(b){const c=this.ctx,f=this.forest,p=this.position(b.x,b.y);if(b.state==='sleeping')return;const s=SPECIES[b.species],scale=Math.max(.58,this.size/560),face=Math.sin(b.phase+b.id)>0?1:-1;const bob=b.state==='foraging'?Math.sin(f.elapsed*6+b.phase)*1.2:Math.sin(f.elapsed*2+b.phase)*.5;c.save();c.translate(p.x,p.y+bob);c.scale(scale*face,scale);c.globalAlpha=b.state==='shelter'?.35:1;
    c.fillStyle='rgba(12,35,17,.16)';c.beginPath();c.ellipse(0,b.state==='flying'?14:7,7,2,0,0,Math.PI*2);c.fill();c.fillStyle='#253f30';c.beginPath();c.moveTo(-4,1);c.lineTo(-13,5);c.lineTo(-6,-2);c.closePath();c.fill();c.fillStyle=s.color;c.beginPath();c.ellipse(0,0,7.2,4.8,-.17,0,Math.PI*2);c.fill();c.fillStyle=b.species===1?'#304139':s.color;c.beginPath();c.arc(5,-3,4,0,Math.PI*2);c.fill();c.fillStyle='#eaddbb';c.beginPath();c.moveTo(8,-3);c.lineTo(12,-1);c.lineTo(8,0);c.closePath();c.fill();c.fillStyle='#192d21';c.beginPath();c.arc(6,-4,1,0,Math.PI*2);c.fill();
    if(b.state==='flying'){const flap=this.reduced?0:Math.sin(f.elapsed*29+b.phase)*8;c.fillStyle='#3d5840';c.beginPath();c.moveTo(-4,0);c.quadraticCurveTo(-10,-10-flap,3,-10-flap);c.lineTo(3,2);c.fill();}else{c.fillStyle=b.species===1?'#6d8070':'#6c614b';c.beginPath();c.ellipse(-2,1,4.7,2.5,.18,0,Math.PI*2);c.fill();}
    c.restore();if(b.singing>0){c.save();c.strokeStyle=`rgba(${f.night>.7?'227,235,173':'87,120,55'},${Math.min(1,b.singing)*.7})`;c.lineWidth=1.4;const size=(Math.sin(f.elapsed*7)*.5+.5)*4;for(let i=0;i<2;i++){c.beginPath();c.arc(p.x,p.y-3,12+size+i*5,-1.05,-.12);c.stroke();}c.restore();}
  }
  drawFireflies(n){const c=this.ctx,f=this.forest;for(const bug of f.fireflies){const t=this.reduced?0:f.elapsed;const p=this.position(bug.x+Math.sin(t*bug.speed+bug.phase)*.017,bug.y+Math.cos(t*bug.speed*.7+bug.phase)*.023);const brightness=(.28+.72*(.5+.5*Math.sin(t*1.7+bug.phase))**3)*n*(1-f.rain*.75);const r=6+brightness*5,g=c.createRadialGradient(p.x,p.y,0,p.x,p.y,r);g.addColorStop(0,`rgba(222,243,151,${brightness*.55})`);g.addColorStop(1,'rgba(215,242,143,0)');c.fillStyle=g;c.beginPath();c.arc(p.x,p.y,r,0,Math.PI*2);c.fill();c.fillStyle=`rgba(238,249,170,${brightness})`;c.beginPath();c.arc(p.x,p.y,1.3,0,Math.PI*2);c.fill();}}
  drawAtmosphere(){const c=this.ctx,f=this.forest,w=this.width,h=this.height;if(f.rain>.025&&!this.reduced){c.save();c.beginPath();c.ellipse(w/2,h*.53,w*.44,h*.43,0,0,Math.PI*2);c.clip();c.strokeStyle=`rgba(194,215,214,${f.rain*.45})`;c.lineWidth=.9;for(let i=0;i<Math.floor(f.rain*125);i++){const x=((i*173.3+f.elapsed*49)%(w+100))-50,y=((i*91.7+f.elapsed*(290+i%35))%(h+90))-45;c.beginPath();c.moveTo(x,y);c.lineTo(x-4-f.wind*7,y+10+i%5);c.stroke();}c.restore();}
    if(f.fog>.1){for(let i=0;i<3;i++){const x=w*(.2+i*.3)+Math.sin(f.elapsed*.06+i)*w*.07,y=h*(.45+i*.075);const g=c.createRadialGradient(x,y,0,x,y,w*.4);g.addColorStop(0,`rgba(220,229,216,${f.fog*.36})`);g.addColorStop(1,'rgba(220,229,216,0)');c.fillStyle=g;c.fillRect(0,0,w,h);}}
    if(f.daylight>.15&&f.rain<.1){for(let i=0;i<12;i++){const p=this.position(.2+((i*.173+Math.sin(f.elapsed*.05+i)*.03)%.62),.3+((i*.131-f.elapsed*.002+10)%.42));c.fillStyle=`rgba(242,231,169,${.3+Math.sin(f.elapsed+i)*.18})`;c.beginPath();c.arc(p.x,p.y,1.2,0,Math.PI*2);c.fill();}}
  }
}
